name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn

    - name: Run Type Check (tsc)
      run: yarn typecheck

    - name: Run ESLint
      run: yarn lint

    - name: Run Jest Unit Tests
      run: npx jest --coverage --coverageReporters json-summary

    - name: Jest Coverage Comment
      id: coverageComment
      uses: MishaKav/jest-coverage-comment@main
      with:
        hide-comment: true
        coverage-summary-path: ./coverage/coverage-summary.json

    - name: Check the output coverage
      run: |
        echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}"
        echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
        echo "Summary HTML - ${{ steps.coverageComment.outputs.summaryHtml }}"

    - name: Update the build status badge
      if: github.ref == 'refs/heads/master'
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.JEST_COVERAGE_COMMENT }}
        gistID: c3e578e189ea5b3c189d7c44c7ff3317
        filename: build-status-comment__main.json
        label: build
        message: ${{ job.status }}
        color: ${{ job.status == 'success' && 'brightgreen' || 'brightred' }}

    - name: Update the coverage badge
      if: github.ref == 'refs/heads/master'
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.JEST_COVERAGE_COMMENT }}
        gistID: ca3d0d92e59bedada3800654ccedcb98
        filename: jest-coverage-comment__main.json
        label: coverage
        message: ${{ steps.coverageComment.outputs.coverage }}
        color: ${{ steps.coverageComment.outputs.color }}